# Evita que o adaptador Realtek Bluetooth entre em suspensão de energia
options btusb enable_autosuspend=n reset=1

# Evita que a economia profunda de energia da Wi-Fi interfira na antena compartilhada do Bluetooth
options rtw88_core disable_lps_deep=y
